name: Build Android APK

on:
  workflow_dispatch: # Allows manual trigger with 1 click
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK with Gradle
        run: ./gradlew assembleDebug --no-daemon

      - name: Rename APK
        run: |
          mkdir -p output
          cp app/build/outputs/apk/debug/app-debug.apk output/Aether-v1.1.0.apk
          sha256sum output/Aether-v1.1.0.apk > output/checksum.txt
          cat output/checksum.txt

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aether-v1.1.0-APK
          path: output/
